# Generated by Django 3.1.5 on 2021-03-04 23:22

from django.db import migrations
import relativefilepathfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=relativefilepathfield.fields.RelativeFilePathField(path='/Users/Tom/PythonProjects/web_portfolio/static/img/'),
        ),
    ]
