# Generated by Django 3.1.5 on 2021-03-04 23:47

from django.db import migrations
import relativefilepathfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210304_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=relativefilepathfield.fields.RelativeFilePathField(default='projects/static/img/project3.png', path='/Users/Tom/PythonProjects/web_portfolio/projects/static/img/'),
        ),
    ]
