# Generated by Django 3.1.5 on 2021-03-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.FilePathField(default='', path='/videos'),
        ),
    ]
