# Generated by Django 3.1.5 on 2021-03-07 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20210307_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='demo',
            field=models.BooleanField(null=True),
        ),
    ]
