# Generated by Django 3.1.5 on 2021-03-07 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20210307_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='demo',
            field=models.BooleanField(default=False),
        ),
    ]
