# Generated by Django 3.1.5 on 2021-03-07 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20210307_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='readme',
            field=models.URLField(default=''),
        ),
    ]
