# Generated by Django 3.1.5 on 2021-02-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'product_description',
            },
        ),
    ]
