# Generated by Django 3.1.5 on 2021-03-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210213_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='statusOf',
            field=models.CharField(default='', max_length=20),
        ),
    ]
